### PR TITLE
Upgrade AngularJS and UI-Bootstrap

### PR DESCRIPTION
**Pull request by garberg**
Upgrade AngularJS and UI-Bootstrap to reasonable recent versions.
* AngularJS 1.5.3 (not the most recent version, but what UI-Bootstrap has been tested with)
* UI-Bootstrap 1.3.3

The original reason behind this was to get tooltips working again (see #887), but I also fixed the comment popups in the prefix list. In addition to this I did some cleanup among the JavaScript libraries and made sure we use minified versions of the libraries.

To get tooltips with HTML working with the new versions I had to disable the Strict Contextual Escaping-feature of AngularJS, see 79b5912 for more details. As a consequence to this it became apparent that NIPAP is vulnerable to an XSS attack where a user could insert elements into the DOM by crafting tags with HTML in them.I've greated #937 to handle this issue.

### CODE REVIEW

**Comment by plajjan** [comment]
I can't review this code. Can only take a look at the result, i.e. look at the UI in a web browser. An idea that I just got around this.. wouldn't it be sweet if we could build docker container for every PR and could ask the nipap-demo machine to spin up a set of containers so it's easy to try out... or maybe I'm thinking too much about something that isn't *that* hard to try out today. Docker container images would be sweet regardless...

**Comment by garberg** [comment]
I agree, this is pretty difficult to review. Spinning up a docker container so the web interface can be manually tested easily is an excellent idea. Sure, it's not very difficult to fetch the PR branch and perform tests locally, but automating it would lower the barrier.

We should also look into introducing unit tests for the parts of the web interface which can be tested. After all that's something which is put forward as a strength with AngularJS.

**Comment by plajjan** [comment]
So it seems our psutil changes have made nipapd incompatible with Ubuntu 14.04 LTS. I think this is fine since 16.04 LTS is out but since my dev laptop is 14.04 it poses a slight challenge to me. Need to upgrade or build containers...

**Comment by plajjan** [comment]
You know how trying to fix one problem leads to finding another problem and in trying to fix that problem you.. yeah, you get it.

I wanted to run this. I couldn't on my current dev env. So I wanted to put it in a docker container, which would be really sweet in lots of ways.. but to do that I wanted to fix a few other things, like #947. I think after #947 I can post some Dockerfiles so that I will be able to run everything in docker and thus I can test this :)

**Comment by plajjan** [comment]
Yay @houndci-bot doing it's best not to be very helpful at all. Lemme see if I can docker the shit out of this PR =)

**Comment by plajjan** [comment]
Neither the prefix comment or any other tooltips (I can't really remember where they are) are working for me :/ Tested using Chrome on Mac OS X with nipap-www served through docker.

**Comment by plajjan** [comment]
My bad yo. Though I'd be clever and tag the image I built for this and then I failed to use the docker compose file I had updated with the tag.

Now that I really tried it out: This thing is working beautifully! LGTM et al. Will merge.

**Pull request merged**
