### PR TITLE
Build python3 pynipap package

### LINKED ISSUE #875: pynipap deb package doesn't support python3
pynipap is compatible with python3, but the debian package only does python2

### PR DESCRIPTION
**Pull request by LordAro**
Also update debian packaging standards version.

Fixes #875

### CODE REVIEW

**Comment by LordAro** [comment]
I haven't checked what buildrpm does, not sure if this is an issue

**Comment by LordAro** [comment]
I'm not convinced the travis failures are mine....

**Comment by plajjan** [comment]
Nice, thanks for PR :)

Travis-CI complains though, seems like python-pynipap wasn't built - https://travis-ci.org/SpriteLink/NIPAP/jobs/105397083#L1214

buildrpm has been in there, kind of dormant, since day 1. Never used it to build official RPMs or anything like that so I don't care if you've broken it since it wasn't really working before anyway ;) Should fix that some day...

**Comment by plajjan** [comment]
Culprit: https://travis-ci.org/SpriteLink/NIPAP/jobs/105397083#L788

```
dh_auto_clean: unable to load build system class 'pybuild': Can't locate Debian/Debhelper/Buildsystem/pybuild.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at (eval 5) line 2.
BEGIN failed--compilation aborted at (eval 5) line 2.
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1350:
dpkg-buildpackage -rfakeroot -D -us -uc failed
make[1]: *** [builddeb] Error 29
make[1]: Leaving directory `/home/travis/build/SpriteLink/NIPAP/pynipap'
```

**Comment by LordAro** [comment]
Ah, missing dependency. I'll fix that

**Comment by LordAro** [comment]
...dh-python is newer than 12.04. dammit travis.

**Comment by plajjan** [comment]
Maybe it's time to have a look at the new environments that Travis has to offer. We are still on their old/legacy platform. They introduced a sudo-less container environment that we can't use since we need root to install postgres extensions et al but now they also have some in between environment that I think runs on GCE and that gives you sudo. Or maybe it's possible to use a different distro even in the legacy environment.

**Comment by LordAro** [comment]
I found https://docs.travis-ci.com/user/trusty-ci-environment/ but yeah, looking at the travis.yml file it would be good to get it a bit "updated"

**Comment by plajjan** [comment]
I'll fix it so it runs on trust (14.04) instead. Please hold :)

**Comment by plajjan** [comment]
Ok, I've merged that stuff to master so builds are now using 14.04. Can you rebase your branch on master and hopefully it should start working :)

**Comment by LordAro** [comment]
Awesome :)

Now, don't suppose I can get a python3-pynipap deb in the repo now...  (yay for restrictive deployments)

**Comment by plajjan** [comment]
I'm working on that but since the last deploy I've moved machines so I need to dig out my pgp key and stuff. Also need to figure out what version to release this as. Usually we keep all packages in sync but I can't just build new 0.28 packages from master since there are more major changes that should bump to 0.29, yet I don't want to release v0.29.0 right now since other stuff should go in there.

Correct way would be to backport to 0.28.x-branch but that involves cherry-picking which is PITA when there are more than 1 commits ;)

Think I can fake it a bit by circumventing parts of the build process and only do a 0.28.4 for python3-pynipap but first I need to have lunch.

**Comment by LordAro** [comment]
I totally understand, no worries if you can't do it

**Pull request merged**
