### PR TITLE
Handle non-ASCII characters in the CLI

### PR DESCRIPTION
**Pull request by garberg**
Some fixes to make the CLI handle non-(7-bit)ASCII characters again. I chose to simply replace all instances of str() with unicode() to keep things simple, even at locations which could not possibly return non-ASCII characters such as prefix lengths.

### CODE REVIEW

**Comment by plajjan** [comment]
So the one thing I have against this is that unicode() doesn't exist in python3. I would much rather move in the direction of always running the CLI with python3. I think py3 exists on all platforms today so it shouldn't really be an issue. Are all the libs we use py3 compatible?

I think the py2&py3 safe way is to do .decode('utf-8') on the input, can you try?

**Comment by plajjan** [comment]
Or we could do some hack, like 
```
import sys
if sys.version_info[0] == 2:
    str = unicode
```

**Comment by garberg** [comment]
Hehe, yep, I wrote something similar in #974 :smile:

I agree, aiming towards Python 3 is the better way forward. There are some other things (exception handling, print statements, ...) which needs to be addressed for full Python 3 compatibility, which is why I chose this easier way forward for now.

I'll do some decode('utf-8'):ing, hang on...

**Comment by plajjan** [comment]
Ok, I get that but I really don't want to take a step in the wrong direction, away from py3 compatibility because then we only adds things to the list of things to do and that's.. well, it's no good.

import the new print statements and change exc handling as well? :)

Does the CLI rely on some py2-only lib?

**Comment by plajjan** [comment]
Not relevant anymore after merge of #976 - we now do full py3 compatible instead of fiddling with .decode() & .encode() in py2.

**Pull request closed without merging**
