### PR TITLE
Add references to backend functions in pynipap docs

### PR DESCRIPTION
**Pull request by garberg**
To avoid duplicating information the pynipap documentation is very brief as most data is passed straight to the backend anyway. This PR tries to make this more clear by adding references to the corresponding backend function to each of the pynipap class methods which involve backend operations.

### CODE REVIEW

**Comment by garberg** [comment]
The result can be seen at http://nipap-garberg.readthedocs.org/en/712-update_pynipap_docs/.

**Comment by garberg** [comment]
@plajjan, any comments to this?

**Comment by plajjan** [comment]
Well, yes, I just have difficulty forming an opinion :P 
Overall I think having references is a good thing but given issues like #750 I'm not convinced we should be linking to the "NIPAP API", which also happens to be a name I don't like, I don't think we should call it an API even if one could consider as such. It is not meant to be interfaced with by normal users. Renaming it isn't necessarily part of this PR though.

So, to focus on your PR, I think it needs to be made clear that the XML-RPC layer is in between pynipap and the NIPAP backend module. Either by linking first to XML-RPC from pynipap or by expressing it in NIPAP API and from NIPAP API linking to XML-RPC API for every function.

**Comment by plajjan** [comment]
Just the wording "For more information, see the backend funtion X" is not a good one. I know you added a piece at the top of the documentation about how we want to keep things in pynipap very "thin" but chances are people are not going to read the documentation top-down. They will go look at the very function they are interested in and for that reason I think the wording of the text that refers to the backend module needs to be understandable on its own. I base this on how I typically read docs ;)

Something more along the lines of:
"pynipap maps directly to the XML-RPC function X, please see the documentation of that function for information on input arguments and return values"

Or "pynipap maps to function X in the backend, please see the documentation of that function for information on input arguments and return values"

In addition, in the backend module, perhaps we should have a section explaining the XML-RPC API and how it wraps around the backend and for every backend function we have a reference saying something along the lines of "This is the documentation of the internal backend function. It is exposed over XML-RPC, please also see the documentation of the XML-RPC function for full understanding.".

**Pull request closed without merging**
