### PR TITLE
Convert java client to use gradle as java build packing system

### PR DESCRIPTION
**Pull request by bbaja42**
This should help in allowing to support latest java versions, as mentioned in #1074
To make the usage same as before, I made sure not to change Makefile usage.

```
➜  jnipap git:(master) make
gradle jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.892 secs
cp build/libs/jnipap.jar .
➜  jnipap git:(master)
```

### CODE REVIEW

**Comment by bbaja42** [comment]
With warnings:
 ````
........... ( skipped large amount of text)
/Users/barisa/src/NIPAP/jnipap/src/main/java/jnipap/VRF.java:31: warning: [rawtypes] found raw type: HashMap
                HashMap attr = new HashMap();
                                   ^
  missing type arguments for generic class HashMap<K,V>
  where K,V are type-variables:
    K extends Object declared in class HashMap
    V extends Object declared in class HashMap
Note: Some input files additionally use unchecked or unsafe operations.
100 warnings

```

**Comment by plajjan** [comment]
This needs to pass CI before merge, will you look at that?

Also, can you explain the choice of Gradle? I'm not intimately familiar with Java build tools. Can you outline the pros of switching to Gradle?

**Comment by bbaja42** [comment]
Hi.
I'll take a look at the CI, and make sure they pass.

Regarding the other question, on why switch to gradle?
Well, I'm familiar with both gradle and maven, and find gradle configuration to setup. They all work perfectly fine; the main reason to switch to any build tool is to get standard java build layout ( which is forced by both maven and gradle).

This all being said, there is no strong reason to switch to any other build tool; if the current maintainers are happy with the current status :). I've started using NIPAP, so I was just looking for some small things I can contribute back.

[Carefully selected link where gradle is shown in good light](http://devopscube.com/list-of-popular-open-source-java-build-tools/)

**Comment by plajjan** [comment]
@garberg does more of the Java stuff so I'll let him have the final word but the rationale for Gradle sounds sane to me :)

**Comment by bbaja42** [comment]
The tests are passing now. At first, they were failing due to gradle version in travis CI being very old. After overriding travis gradle, with local gradle; now they are all passing. With this, gradle packaged the app using java 1.6. Afaik, there is nothing stopping 1.7 and 1.8 from working as well.

**Comment by plajjan** [comment]
@bbaja42 there are now binary files included in this PR - are they really needed? The whole .gradle/ directory seems like build output rather than source files.

**Comment by bbaja42** [comment]
Oh, thnx for that; I had thought I removed them, my mistake.
Thought I had to leave in one jar, for gradle-wrapper, which is necessary to download latest gradle ( version in travis is 2.0, which is quite old)

https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by plajjan** [comment]
I'd really like to avoid binary files in the git repo. Can't you download the gradle wrapper jar in the Makefile or .travis-ci.yml ?

**Comment by bbaja42** [comment]
Cool, I'll try to get it via travis-ci

**Comment by bbaja42** [comment]
I was able to swap back to gradle deployed with travis, by using mavenRepository instead of default gradle one.
With this, there is no need for gradle wrapper; so no binary files in the git.

**Comment by plajjan** [comment]
So I just wanted to let you know that @garberg is on vacation so he won't be able to look at this until he's back.. hold tight! :)

**Comment by bbaja42** [comment]
Thnx, I'm in no hurry, this is just a small thing

**Comment by garberg** [comment]
This looks great to me; neither I am versed in the world of Java build tools but gradle seems as a good choice. I've wanted to implement Maven or such but not really gotten around to do it. One of the main drivers for me was automatic downloading of dependencies, to avoid keeping them in the NIPAP repo.

Unfortunately there are some conflicts, if you resolve them I'd be happy to merge!

**Comment by bbaja42** [comment]
Great, I merged from the master, so there are no more conflicts.

Since you mentioned your driver was to remove having dependancies in the repo, I'll fix that tonight ( should be easy with gradle, it uses same dependency management repo as maven)

**Comment by garberg** [comment]
Nice work!

**Pull request merged**
